Line_2 $$ public void testNew6() throws Exception -->Line_15 $$ Exception exception = futureTask.get()[ CD ]
Line_2 $$ public void testNew6() throws Exception -->Line_14 $$ thread.start()[ CD ]
Line_2 $$ public void testNew6() throws Exception -->Line_16 $$ Assert.assertNull(exception)[ CD ]
Line_2 $$ public void testNew6() throws Exception -->Line_3 $$ FutureTask<Exception> futureTask = new FutureTask<Exception>(new Callable<Exception>() [ CD ]
Line_3 $$ FutureTask<Exception> futureTask = new FutureTask<Exception>(new Callable<Exception>() -->Line_15 $$ Exception exception = futureTask.get()[ FD ]
Line_3 $$ FutureTask<Exception> futureTask = new FutureTask<Exception>(new Callable<Exception>() -->Line_10 $$ return null[ CD ]
