Line_2 $$ private void assertValidationFails(TaskInternal task, String... expectedErrorMessages) -->Line_16 $$ assertThat(actualMessages, equalTo(new HashSet<String>(Arrays.asList(expectedErrorMessages))))[ FD ]
Line_12 $$ HashSet<String> actualMessages = new HashSet<String>()-->Line_16 $$ assertThat(actualMessages, equalTo(new HashSet<String>(Arrays.asList(expectedErrorMessages))))[ FD ]
Line_13 $$ for (Throwable cause : e.getCauses()) -->Line_14 $$ actualMessages.add(cause.getMessage())[ FD ]
Line_7 $$ if (expectedErrorMessages.length == 1) -->Line_8 $$ assertThat(e.getMessage(), containsString("A problem was found with the configuration of " + task))[ CD ]
Line_12 $$ HashSet<String> actualMessages = new HashSet<String>()-->Line_14 $$ actualMessages.add(cause.getMessage())[ FD ]
Line_7 $$ if (expectedErrorMessages.length == 1) -->Line_10 $$ assertThat(e.getMessage(), containsString("Some problems were found with the configuration of " + task))[ CD ]
Line_2 $$ private void assertValidationFails(TaskInternal task, String... expectedErrorMessages) -->Line_4 $$ task.execute()[ FD ]
