Line_2 $$ public void testDataSourceDefinition() throws Exception -->Line_3 $$ Connection conn = null[ CD ]
Line_6 $$ conn = ds.getConnection()-->Line_8 $$ conn.close()[ FD ]
Line_6 $$ conn = ds.getConnection()-->Line_14 $$ conn.close()[ FD ]
Line_6 $$ conn = ds.getConnection()-->Line_7 $$ testConnection(conn, "select user()", user1)[ FD ]
Line_6 $$ conn = ds.getConnection()-->Line_9 $$ conn = ds.getConnection(user2, user2)[ FD ]
Line_9 $$ conn = ds.getConnection(user2, user2)-->Line_12 $$ if (conn != null) [ FD ]
Line_3 $$ Connection conn = null-->Line_6 $$ conn = ds.getConnection()[ FD ]
Line_3 $$ Connection conn = null-->Line_14 $$ conn.close()[ FD ]
Line_6 $$ conn = ds.getConnection()-->Line_12 $$ if (conn != null) [ FD ]
Line_3 $$ Connection conn = null-->Line_8 $$ conn.close()[ FD ]
Line_9 $$ conn = ds.getConnection(user2, user2)-->Line_10 $$ testConnection(conn, "select user()", user2)[ FD ]
Line_3 $$ Connection conn = null-->Line_10 $$ testConnection(conn, "select user()", user2)[ FD ]
Line_6 $$ conn = ds.getConnection()-->Line_10 $$ testConnection(conn, "select user()", user2)[ FD ]
Line_3 $$ Connection conn = null-->Line_12 $$ if (conn != null) [ FD ]
Line_3 $$ Connection conn = null-->Line_7 $$ testConnection(conn, "select user()", user1)[ FD ]
Line_3 $$ Connection conn = null-->Line_9 $$ conn = ds.getConnection(user2, user2)[ FD ]
Line_9 $$ conn = ds.getConnection(user2, user2)-->Line_14 $$ conn.close()[ FD ]
