Line_2 $$ public void testAccessThroughVaultDatasource() throws Exception -->Line_14 $$ assertEquals(rs.getString("Name"), "John")[ CD ]
Line_2 $$ public void testAccessThroughVaultDatasource() throws Exception -->Line_6 $$ Connection con = null[ CD ]
Line_2 $$ public void testAccessThroughVaultDatasource() throws Exception -->Line_12 $$ ResultSet rs = con.prepareStatement("SELECT Name FROM TestPeople WHERE Surname='Smith'").executeQuery()[ CD ]
Line_2 $$ public void testAccessThroughVaultDatasource() throws Exception -->Line_3 $$ Context initialContext = new InitialContext()[ CD ]
Line_4 $$ DataSource ds = (DataSource) initialContext.lookup("java:jboss/datasources/" + VAULT_BLOCK)-->Line_5 $$ Assert.assertNotNull(ds)[ FD ]
Line_6 $$ Connection con = null-->Line_12 $$ ResultSet rs = con.prepareStatement("SELECT Name FROM TestPeople WHERE Surname='Smith'").executeQuery()[ FD ]
Line_12 $$ ResultSet rs = con.prepareStatement("SELECT Name FROM TestPeople WHERE Surname='Smith'").executeQuery()-->Line_13 $$ rs.next()[ FD ]
Line_2 $$ public void testAccessThroughVaultDatasource() throws Exception -->Line_15 $$ con.close()[ CD ]
Line_8 $$ con = ds.getConnection()-->Line_12 $$ ResultSet rs = con.prepareStatement("SELECT Name FROM TestPeople WHERE Surname='Smith'").executeQuery()[ FD ]
Line_4 $$ DataSource ds = (DataSource) initialContext.lookup("java:jboss/datasources/" + VAULT_BLOCK)-->Line_8 $$ con = ds.getConnection()[ FD ]
Line_12 $$ ResultSet rs = con.prepareStatement("SELECT Name FROM TestPeople WHERE Surname='Smith'").executeQuery()-->Line_14 $$ assertEquals(rs.getString("Name"), "John")[ FD ]
Line_2 $$ public void testAccessThroughVaultDatasource() throws Exception -->Line_4 $$ DataSource ds = (DataSource) initialContext.lookup("java:jboss/datasources/" + VAULT_BLOCK)[ CD ]
Line_3 $$ Context initialContext = new InitialContext()-->Line_4 $$ DataSource ds = (DataSource) initialContext.lookup("java:jboss/datasources/" + VAULT_BLOCK)[ FD ]
Line_6 $$ Connection con = null-->Line_8 $$ con = ds.getConnection()[ FD ]
Line_6 $$ Connection con = null-->Line_15 $$ con.close()[ FD ]
Line_2 $$ public void testAccessThroughVaultDatasource() throws Exception -->Line_13 $$ rs.next()[ CD ]
Line_8 $$ con = ds.getConnection()-->Line_15 $$ con.close()[ FD ]
Line_2 $$ public void testAccessThroughVaultDatasource() throws Exception -->Line_5 $$ Assert.assertNotNull(ds)[ CD ]
