Line_6 $$ final IOException ioException = new IOException()-->Line_25 $$ Assert.assertSame(ioException, logRecord.getThrown())[ FD ]
