Line_7 $$ if (t.getClass() == exceptionClass)-->Line_8 $$ threw = true[ CD ]
Line_2 $$ private static void checkThrowsException(Callable<Object> c, Class<?> exceptionClass) -->Line_3 $$ boolean threw = false[ CD ]
Line_3 $$ boolean threw = false-->Line_10 $$ Assert.assertTrue(threw)[ FD ]
Line_3 $$ boolean threw = false-->Line_8 $$ threw = true[ FD ]
Line_2 $$ private static void checkThrowsException(Callable<Object> c, Class<?> exceptionClass) -->Line_7 $$ if (t.getClass() == exceptionClass)[ FD ]
Line_2 $$ private static void checkThrowsException(Callable<Object> c, Class<?> exceptionClass) -->Line_10 $$ Assert.assertTrue(threw)[ CD ]
Line_8 $$ threw = true-->Line_10 $$ Assert.assertTrue(threw)[ FD ]
Line_2 $$ private static void checkThrowsException(Callable<Object> c, Class<?> exceptionClass) -->Line_5 $$ c.call()[ FD ]
