Line_5 $$ EdtTestUtil.runInEdtAndWait(new Runnable() -->Line_7 $$ Disposer.dispose(myTestRootDisposable)[ CD ]
Line_2 $$ public void tearDown() throws Exception -->Line_4 $$ Assert.assertFalse("tearDown() already has been called", myDisposed)[ CD ]
Line_2 $$ public void tearDown() throws Exception -->Line_3 $$ Assert.assertTrue("setUp() has not been called", myInitialized)[ CD ]
Line_2 $$ public void tearDown() throws Exception -->Line_11 $$ resetClassFields(getClass())[ CD ]
Line_2 $$ public void tearDown() throws Exception -->Line_5 $$ EdtTestUtil.runInEdtAndWait(new Runnable() [ CD ]
