Line_6 $$ Throwable cause = ex.getRootCause()-->Line_8 $$ assertTrue("Cannot resolve method 'myBeforeAdvice' to a unique method", cause.getMessage().indexOf("Cannot resolve method 'myBeforeAdvice' to a unique method") != -1)[ FD ]
