Line_3 $$ GetAttributeProcessCallable getAttributeProcessCallable = new GetAttributeProcessCallable(_testClassObjectName, "NameX", false)-->Line_5 $$ getAttributeProcessCallable.call()[ FD ]
Line_8 $$ Throwable throwable = pe.getCause()-->Line_9 $$ Assert.assertSame(AttributeNotFoundException.class, throwable.getClass())[ FD ]
Line_2 $$ public void testGetAttributeProcessCallableFailureInstanceRequired() -->Line_3 $$ GetAttributeProcessCallable getAttributeProcessCallable = new GetAttributeProcessCallable(_testClassObjectName, "NameX", false)[ CD ]
