Line_2 $$ private void throwSimpleExceptionIfPossible(Object value, AccessException ex) -->Line_3 $$ if (ex.getCause() instanceof InvocationTargetException) [ CD ]
Line_2 $$ private void throwSimpleExceptionIfPossible(Object value, AccessException ex) -->Line_4 $$ Throwable rootCause = ex.getCause().getCause()[ FD ]
Line_3 $$ if (ex.getCause() instanceof InvocationTargetException) -->Line_5 $$ if (rootCause instanceof RuntimeException) [ CD ]
Line_2 $$ private void throwSimpleExceptionIfPossible(Object value, AccessException ex) -->Line_8 $$ throw new ExpressionInvocationTargetException(getStartPosition(), "A problem occurred when trying to execute method '" + this.name + "' on object of type [" + value.getClass().getName() + "]", rootCause)[ FD ]
Line_2 $$ private void throwSimpleExceptionIfPossible(Object value, AccessException ex) -->Line_3 $$ if (ex.getCause() instanceof InvocationTargetException) [ FD ]
Line_3 $$ if (ex.getCause() instanceof InvocationTargetException) -->Line_4 $$ Throwable rootCause = ex.getCause().getCause()[ CD ]
Line_4 $$ Throwable rootCause = ex.getCause().getCause()-->Line_5 $$ if (rootCause instanceof RuntimeException) [ FD ]
