Line_3 $$ Class<?> testClass = prepareTest()-->Line_5 $$ testClass.getMethod("foo", Object.class, Object.class).invoke(testClass.newInstance(), null, null)[ FD ]
Line_2 $$ public void testCustomExceptionType() throws Exception -->Line_3 $$ Class<?> testClass = prepareTest()[ CD ]
